if (NOT CMAKE_SYSTEM_NAME)
	SET( CMAKE_SYSTEM_NAME Linux)
endif()
SET( TOOLCHAIN Linux)
SET( LIBRARY_PREFIX lib)
SET( LIBRARY_SUFFIX .so)
message(STATUS "Toolchain Ubuntu")

# SET (TOOLCHAIN_PREFIX aarch64-openwrt-linux-gnu-)
SET (TOOLCHAIN_PREFIX aarch64-linux-gnu-)
SET (TOOLCHAIN_ROOT /opt/toolchain/gcc/gcc-linaro-aarch64-linux-gnu)
# SET (TOOLCHAIN_ROOT $ENV{HOME}/envx/toolchain/gcc/gcc-linaro-aarch64-linux-gnu)
if (EXISTS ${TOOLCHAIN_ROOT})
	SET (TOOLCHAIN_PREFIX ${TOOLCHAIN_ROOT}/bin/aarch64-linux-gnu-)
	# SET (TOOLCHAIN_PREFIX ${TOOLCHAIN_ROOT}/bin/aarch64-openwrt-linux-gnu-)
endif()

# set cmake toolchains
SET( CMAKE_MAKE_PROGRAM /usr/bin/make    CACHE PATH "Linux Make Program" )
SET( CMAKE_SH           /bin/sh      CACHE PATH "Linux shell Program" )
SET( CMAKE_AR           ${TOOLCHAIN_PREFIX}ar      CACHE PATH "Linux ar Program" )
SET( CMAKE_RANLIB       ${TOOLCHAIN_PREFIX}ranlib      CACHE PATH "Linux ranlib Program" )
SET( CMAKE_NM           ${TOOLCHAIN_PREFIX}nm      CACHE PATH "Linux nm Program" )
SET( CMAKE_OBJCOPY      ${TOOLCHAIN_PREFIX}objcopy CACHE PATH "Linux objcopy Program" )
SET( CMAKE_OBJDUMP      ${TOOLCHAIN_PREFIX}objdump CACHE PATH "Linux objdump Program" )
SET( CMAKE_LINKER       ${TOOLCHAIN_PREFIX}ld     CACHE PATH "Linux Linker Program" )
SET( CMAKE_STRIP        ${TOOLCHAIN_PREFIX}strip   CACHE PATH "Linux Strip Program" )
SET( CMAKE_C_COMPILER  ${TOOLCHAIN_PREFIX}gcc )
SET( CMAKE_CXX_COMPILER  ${TOOLCHAIN_PREFIX}g++)

SET( CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_ROOT}/bin)
SET( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
SET( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
SET( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )


add_definitions("-DLINUX")
add_definitions("-DKANZI_V8_API=")
add_definitions("-DKZ_SUPPORT_GRAPHICS_API_OPENGL=1")
add_definitions("-DKZ_RUNTIME_GRAPHICS_BACKEND=1")
add_definitions("-DKZ_DLOAD_GLES_SYMBOLS=32")
add_definitions("-DNODEBUG")
add_definitions("-DKANZI_FEATURE_3D")
add_definitions("-DPNG_NO_MMX_CODE")
add_definitions("-DX11")
add_definitions("-DGLX")
add_definitions("-DKZ_SUPPORT_GRAPHICS_CONTEXT_API_GLX=1")
add_definitions("-DKZ_DLOAD_GL_SYMBOLS=13")

set(CMAKE_CXX_FLAGS "-fexceptions -O2 -fPIC -Wall -Wextra -Wno-overlength-strings -fno-strict-aliasing -Wno-maybe-uninitialized -Wno-long-long -pthread")
